version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels: [ '🤖 Dependencies', 'skip-changelog' ]
    commit-message:
      prefix: "chore"
    groups:
      go-dependencies:
        patterns: [ "*" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels: [ '🛡️ Infrastructure / CI', 'skip-changelog' ]
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 5